# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paul Anderson, Web Developer
email: paul@andersonpaul.com
description: >
  Thank you for visiting. Please feel free to use any of the methods listed here
  to get in touch with me. I am currently open to new work opportunities, and I
  would love to hear about what you are doing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.andersonpaul.com" # the base hostname & protocol for your site
personal_name: Paul Anderson
twitter_username: bpaulanderson
github_username:  b-paul
collections:
  - skills
  - contribs
  - projects

# Build settings
markdown: kramdown
exclude:
  - resume.pages
